# Generated by Django 5.0.6 on 2024-05-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcat',
            name='product_image',
            field=models.ImageField(upload_to='product_images\\samsung.jpg'),
        ),
    ]
